  proxy: "direct"
  # uncomment line below for temporary local development of module
  # replacements = "github.com/google/docsy -> ../../docsy"
  hugoVersion:
    extended: true
    min: "0.73.0"
  imports:
    - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-decap-cms
      disable: true
    - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-netlify
      disable: true
    - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-bootstrap/v5
      disable: true
    - path: "github.com/google/docsy"
      disable: false
    - path: "github.com/google/docsy/dependencies"
      disable: false
