# --------------------------------------------------------------------
# 
# Permalinks
# 
# Define a URL pattern for each top-level section.
# 
# see: https://gohugo.io/content-management/urls/#permalinks
#
blog: '/:section/:year/:month/:day/:slug/'

authors: '/author/:slug/'
tags: '/tag/:slug/'
categories: '/category/:slug/'
publication_types: '/publication-type/:slug/'